### ISSUE TITLE
IRSA timeout

### ISSUE THREAD

**Issue by FernandoMiguel** [aws-ia/terraform-aws-eks-blueprints#1008]
## Description

We are experiencing timeouts during destroy and will provide a PR to increase the timeout from the [default 5 min](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace_v1#delete) to 15 min (the max of the login token).

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

### Terminal Output Screenshot(s)

```
module.base_system.module.external_secrets[0].module.eks_blueprints_kubernetes_addons_external_secrets.module.helm_addon.module.irsa[0].kubernetes_namespace_v1.irsa[0]: Still destroying... [id=external-secrets-system, 4m50s elapsed]
╷
│ Error: context deadline exceeded
│
```

**Comment by Zvikan** [comment]
Thank you, In your case, increasing the timeout fixed the issue for you? From my experience so far when a namespace is not being cleaned up properly, most of the times it's because there are some leftover resources in that namespace that are not necessarily managed by TF (classic example around CRDs), which causes the namespace to be "stuck" in "Deleting" state. I've yet to see a case where increasing the timeout helps but happy to learn more from you.

**Comment by FernandoMiguel** [comment]
Usually running a second destroy works.. Seems it's taking longer and keeps running in the background.
Tested against my PR branch and had success.
I'll keep using it for a few more days to see if that long is fine.
From experience of manually deleting namespaces, I know they take a decent amount of time.
So just a tad more than 5 mins should work for us, and ideally others.
Can also make it a variable and set it to null.
15 min felt OK cause that's how long the kubernetes token is anyway.
