### ISSUE TITLE
[ADDON] - Robusta

### ISSUE THREAD

**Issue by armujahid** [aws-ia/terraform-aws-eks-blueprints#1015]
Add support for [Robusta](https://docs.robusta.dev/master/index.html) as an add-on. It's an open source platform for Kubernetes troubleshooting.

Installation: https://docs.robusta.dev/master/installation.html

**Comment by florentio** [comment]
Hello @armujahid, installation of robusta in kubernetes cluster needs a generation of a custom values as mentionnes here https://docs.robusta.dev/master/installation.html#creating-the-config-file
The addon will not succeds github action check unless we setup a generated values with sink configuration and added to the module by using the link above

Sink configuration is required and we must setup it by choosing of one the solution here https://docs.robusta.dev/master/catalog/sinks/index.html

I am wondering how can we setup a seek in the value file because this has to be valid configuration.

**Comment by bryantbiggs** [comment]
thank you for the issue - at this time we will not be adding this implementation to the project. if you wish to use Robusta you can utilize the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) resource to add support in your environment
