### ISSUE TITLE
cluster_security_group_additional_rules conflicts CIDR blocks

### ISSUE THREAD

**Issue by mballoni** [aws-ia/terraform-aws-eks-blueprints#1018]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

I'm playing with terraform-aws-eks-blueprints and trying to "mimic" an EKS we have here where all the heavy lifting is done manually.
In short, in our setup we have a cluster security group with a few rules, specially to allow our peerings to communicate with our cluster.
When I try to replicate it using the blueprints, such as (there are many other rules, but they all fail even when I set just one for testing):

```
  cluster_service_ipv4_cidr = "10.205.0.0/16"
  
  create_cluster_security_group           = true
  
  cluster_security_group_additional_rules = {
    my_special_peering = {
      cidr_blocks                = [10.50.0.0/16]
      description                = "Allow traffic from special peering"
      protocol                   = "all"
      from_port                  = 0
      to_port                    = 65535
      type                       = "ingress"
      source_node_security_group = true
    }
}
```

I get the following errors:

```
│ Error: Conflicting configuration arguments
│ 
│   with module.runners_cluster.module.aws_eks.aws_security_group_rule.cluster["my_special_peering"],
│   on .terraform/modules/runners_cluster.aws_eks/main.tf line 186, in resource "aws_security_group_rule" "cluster":
│  186:   cidr_blocks      = try(each.value.cidr_blocks, null)
│ 
│ "cidr_blocks": conflicts with source_security_group_id

│ Error: Conflicting configuration arguments
│ 
│   with module.runners_cluster.module.aws_eks.aws_security_group_rule.cluster["my_special_peering"],
│   on .terraform/modules/runners_cluster.aws_eks/main.tf line 190, in resource "aws_security_group_rule" "cluster":
│  190:   source_security_group_id = try(
│  191:     each.value.source_security_group_id,
│  192:     try(each.value.source_node_security_group, false) ? local.node_security_group_id : null
│  193:   )
│ 
│ "source_security_group_id": conflicts with cidr_blocks

```

I'm checking the source code in the hopes I'll figure out whats going on but my knowledge is limited here
Any hints?

I'll be happy to provide additional context if needed.

Thank you folks!

**Comment by mballoni** [comment]
Additional context (may be unrelated, or not). 
If I comment out the additional rules it fails on a data health check before moving on the **planning**:

```
╷
│ Error: Error making request: Get "https://[REDACTED].eks.amazonaws.com/healthz": dial tcp 10.105.1.56:443: connect: connection timed out
│ 
│   with module.runners_cluster.data.http.eks_cluster_readiness[0],
│   on .terraform/modules/runners_cluster/data.tf line 12, in data "http" "eks_cluster_readiness":
│   12: data "http" "eks_cluster_readiness" {
│ 
```

**Comment by bryantbiggs** [comment]
this is correct behavior, you cannot have both a CIDR block and a source security group https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#cidr_blocks

Because the module is aware of the node security group (and cluster security group), we have added this custom variable `source_node_security_group` in order to allow users to use the node security group as a source security group in the rules. So your rule should specify a CIDR, `self`, or a source security group but not any combination of those

**Comment by mballoni** [comment]
@bryantbiggs got it!! So if I keep the CIDR_BLOCK and remove the source_node_security_group = true it should work as expected!
In this case I'm stuck in the second scenario, but I suspect it can be completely unrelated to the issue described.
Would you have any tips on the later issue?

Thank you, I appreciate your help!

**Comment by mballoni** [comment]
@bryantbiggs its running from another EKS (our CI runners) from the same AWS account and VPC this new EKS is being created. 

I have two rules that I thought would be enough for this communication:

```
    cluster_https_b = {
      cidr_blocks                = [var.cidr_block]
      protocol                   = "tcp"
      from_port                  = 443
      to_port                    = 443
      type                       = "ingress"
    },
    internal_traffic_b = {
      cidr_blocks                = [var.cidr_block]
      protocol                   = "all"
      from_port                  = 0
      to_port                    = 65535
      type                       = "ingress"
    }
```

this `var.cidr_block` is the same CIDR from the same VPC that both EKSs exists and the CI runners have the exactly same configuration (I'm attempting to create a future replacement with a better setup).

Am I missing something?

Again, I appreciate your help and patience with me, I understand I may have run out of the original question scope.

**Comment by mikeinton** [comment]
@mballoni - If both source and destination EKS clusters are in the same AWS Account/VPC then are rules tied to CIDR blocks  required here?  Couldn't you permit access via security group ID's from your other EKS cluster instead?

I don't know if this entirely fits your requirements but in my case, I need the following connectivity requirements for my EKS clusters created by these blueprints.

`Public Internet (permit allowlist CIDR's) --> Kubernetes API`
I need to have the ELB fronting kube-api to be exposed publicly which works great as `cluster_endpoint_public_access` defaults to `true` & I can define a list of CIDR's via `cluster_endpoint_public_access_cidrs`

It seems like what you're trying to achieve with your `cluster_https_b` could be similar.  For my case, since I wanted it to be exposed publicly but locked down to an allow list of CIDR's, this works as expected.

```hcl
cluster_endpoint_public_access_cidrs = [
  "x.x.x.x",
  "x.x.y.y",
  "y.y.x.x"
]
```

For your case, since it seems like you need intra VPC communication then enabling `cluster_endpoint_private_access` could be a better option. I'm not familiar with private endpoint only kube-api EKS clusters so it's probably worth reading through the docs [here](https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#private-access).

For the other direction, outbound from `EKS pods/nodes --> EC2/etc within my VPC`, I was able to modify the destination security groups rules to allow inbound access from the node security groups created by these modules.  Here's an example.

```hcl
resource "aws_security_group_rule" "allow_worker_sg" {
  description              = "From EKS ${var.cluster_name} worker security group"
  type                     = "ingress"
  from_port                = 0
  to_port                  = 65535
  protocol                 = "-1"
  source_security_group_id = module.eks_blueprints.worker_node_security_group_id
  security_group_id        = var.default_security_group_id
}
```

Where `var.default_security_group_id` is the ID of security group associated with the various destinations that my EKS pods need to reach.

Again I'm not entirely sure that this fits your use case but I hope that some of this information helps solve your issue.
