### ISSUE TITLE
Allow conditional removal of SSM or SecretsManager access in external-secrets IRSA policy

### ISSUE THREAD

**Issue by domeales-paloit** [aws-ia/terraform-aws-eks-blueprints#1021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

I would like the SSM and SecretsManager sections of the IRSA policy to be dynamic, so they can be removed if the related input ARN list is empty.

#### Describe the solution you would like

For: `data.tf`
```
data "aws_iam_policy_document" "external_secrets" {
  dynamic "statement" {
    for_each = length(var.external_secrets_ssm_parameter_arns) > 0 ? { enabled : true } : {}
    content {
      actions   = ["ssm:GetParameter"]
      resources = var.external_secrets_ssm_parameter_arns
    }
  }
  
  dynamic "statement" {
    for_each = length(var.external_secrets_secrets_manager_arns) > 0 ? { enabled : true } : {}
    content {
      actions = [
        "secretsmanager:GetResourcePolicy",
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret",
        "secretsmanager:ListSecretVersionIds",
      ]
      resources = var.external_secrets_secrets_manager_arns
    }
  }
}
```

#### Describe alternatives you have considered

I can't see an alternative apart from attaching an additional policy that removes the access that the module adds.

#### Additional context

-

**Comment by florentio** [comment]
Hello @domeales-paloit 
Your solution will work only if at least one of the variable `var.external_secrets_secrets_manager_arns` `var.external_secrets_secrets_manager_arns` is not empty list.

 Otherwise the policy document will be invalid and terraform will failed with this error  `MalformedPolicyDocument: Syntax errors in policy.`
A solution will be to add  `count = length(var.external_secrets_ssm_parameter_arns) + length(var.external_secrets_secrets_manager_arns) > 0 ? true : false` but this will affect all the dependencies.

Keep in mind that according to the documentation here https://github.com/external-secrets/kubernetes-external-secrets#secrets-manager-access, `external_secrets` needs access to SSM and or SecretManager and IRSA is the best way to grant permission to the  external_secrets pods. The built-in policy is there to provide minimum policy required by the addon and you can still use `var.irsa_policies` to overwrite the policies to be attached

**Comment by domeales-paloit** [comment]
@florentio Thank you for getting back to me.

Yes you are right, and I agree that the terraform should fail if someone configures the two lists to be empty. I don't see that as a problem as it highlights an issue with the input variables that the user has configured.

The problem as I see it is that the module forces me to give access to SSM, which does not follow a least-privilege approach in my use case where only AWS SecretsManager is in use.

This is a security loophole, and as a security conscious engineer I need to create an additional policy and use `var.irsa_policies` to Deny all SSM keys and all secrets that should not be accessed to ensure that `external-secrets` can only access the secrets that it should be able to access.

I agree that the current design allows the addon to be used in a simple way, I am just not sure that giving full access to all SSM keys and all secrets is the best idea...

**Comment by florentio** [comment]
@domeales-paloit I understand your concern.
If you don't want to allow access to SSM, I think it is better to use `var.irsa_policies` to deny the access granted by the built-in permission.

I think it is better to keep the module as is which is the common usage (grant both permission access and add the ability to changes ARNs through `var.external_secrets_secrets_manager_arns` and `var.external_secrets_ssm_parameter_arns`)

Your use case is special instead of making changes to the module, I would prefer as you also mentioned to use `var.irsa_policies` to Deny all SSM keys and all secrets that should not be accessed by external-secrets.

**Comment by domeales-paloit** [comment]
@florentio Thanks, I will do that for my case.

I don't think my use case is special. I think it would be rare for most real-world situations to full access to all your SSM parameters and secrets to a single runtime tool. I would argue that the current out-of-the box design is probably not suitable for production, but that is just my opinion.

**Comment by asychev** [comment]
I agree with @domeales-paloit, this is not the special case. The recommended secure method should be [EKS Service Account credentials](https://external-secrets.io/main/provider/aws-secrets-manager/#eks-service-account-credentials) which allows ESO to run without any credentials by default. Even [example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/external-secrets/main.tf#L154) in this repository use that method.

@florentio Please, consider reopening this issue.
