### ISSUE TITLE
Private repo kustomize app

### ISSUE THREAD

**Issue by vitiho** [aws-ia/terraform-aws-eks-blueprints#1041]
## Description

Whenever I add ssh key for the private repo in kustomize_app, planing fails. If I remove ssh-key it works fine.

## Versions

- v4.12.1

- Terraform version:
Terraform v1.1.8
- Provider version(s):
LT-TBRUZAS:tf-local tbruzas$ terraform providers -version
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.32.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.8.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]
`  argocd_applications = {
    kustomize_apps = {
      /*
      This points to a single application with no overlays, but it could easily
      point to a a specific overlay for an environment like "dev", and/or utilize
      the ArgoCD app of apps model to install many additional ArgoCD apps.
    */
      path                = "dev/"
      repo_url            = "git@private_repo/argonauts.git"
      project             = "default"
      add_on_application  = true
      ssh_key_secret_name = "github-ssh-key" # Needed for private repos
      insecure            = false
      type                = "kustomize"
    }
  }

  enable_ingress_nginx = true
  #enable_aws_for_fluentbit            = true
  #enable_aws_load_balancer_controller = true
  enable_cluster_autoscaler = true
  enable_metrics_server     = true
  enable_prometheus         = true
}`

run terraform plan, it gives the error:

<img width="1736" alt="Screen Shot 2022-10-10 at 5 12 24 AM" src="https://user-images.githubusercontent.com/3698096/194863869-e515078f-24f9-48f5-acd8-ac57fa48c2a4.png">

## Expected behaviour

If you comment out the key part:
`# ssh_key_secret_name = "github-ssh-key" # Needed for private repos`

Planning is successful.

**Comment by mikeinton** [comment]
@vitiho - I think "github-ssh-key" should be the name of the AWS Secret that you have to create which contains the SSH key for your private repository.

`ssh_key_secret_name = "name-of-aws-secret"`

See this doc for more info - https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/1169e871dd2ceb8104aca87607d5fff25dc9b3fb/docs/add-ons/argocd.md#private-repositories

---
**Private Repositories**
In order to leverage ArgoCD with private Git repositories, you must supply a private SSH key to Argo. The framework provides support for doing so via an integration with AWS Secrets Manager.

To leverage private repositories, do the following:

1. Create a new secret in AWS Secrets Manager for your desired region. The value for the secret should be a private SSH key for your Git provider.
2. Set the ssh_key_secret_name in each Application's configuration as the name of the secret.

Internally, the framework will create a Kubernetes Secret, which ArgoCD will leverage when making requests to your Git provider. See the example configuration below.

---

**Comment by vitiho** [comment]
yes, it should be the AWS Secret name, which it is (I have AWS Secret name called github-ssh-key), it works fine with helm chart, but kustomize type gives that error.
