### ISSUE TITLE
❓ VPC Example with Custom Security Group

### ISSUE THREAD

**Issue by AErmie** [aws-ia/terraform-aws-eks-blueprints#1065]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

In the [eks-cluster-with-new-vpc](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-new-vpc) example, in the VPC module, it includes managing the default network ACL, route table, and security group. 

It would be helpful to have an example where we do not manage the default network security group, etc., but instead create a custom one (for companies that require that).

#### Provide a link to the example/module related to the question

[https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/main.tf](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/main.tf)

**Comment by bryantbiggs** [comment]
Hi @AErmie , what outcome are you looking for? The default security group created by the VPC module are not used by the EKS cluster or its resources created. It is also created by default - but users can create their own security groups as needed

**Comment by bryantbiggs** [comment]
So let me clarify - all of those things are created by default when a VPC is created. A default network ACL, a default route table, and a default security group. No matter what, when you create a VPC, those things will be created. When we say "manage" here, its meaning that we are adopting some level of control over the resources with terraform - i.e., manage it so that we can apply tags and names to the resources to make it clear what they are used for

However, the default security group of the VPC is not used anywhere in this module. If you wish to create a custom security group you can refer to this module https://github.com/terraform-aws-modules/terraform-aws-security-group

**Comment by bryantbiggs** [comment]
closing with information provided
