### ISSUE TITLE
[BUG] terraform destroy fails with argocd enabled

### ISSUE THREAD

**Issue by askulkarni2** [aws-ia/terraform-aws-eks-blueprints#1114]
An attempt to destroy the TF stack using “Terraform destroy” times out as the addons module with argocd times out from being deleted leaving the “argocd” namespace in “Terminating” state. This was observed in multiple tests with attempts to delete “workloads” in the addons module first, followed by trying to destroy/delete the addon module alone.

This is an undocumented known issue. This likely happens because some add-ons like LBC provision external resources which are not cleanly deleted when tf destroy is down without cleaning out workloads first. Using a finalizer cleans it up but it’s not an ideal devex.

**Comment by Zvikan** [comment]
related to https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/865

**Comment by timblaktu** [comment]
@Zvikan @bryantbiggs thanks for this - I hope this will resolve the many destroy-time issues I've been having using eks-blueprints with argocd addon deploying the crossplane addon. Since upgrading to 0.14 a few days ago, I've been getting orphaned IAM Policies created by Crossplane (*-aws-provider-irsa and *-aws-jet-provider-irsa). I have been following the suggested -targeted destroy sequence.

I first was going to try the "Terraform" approach, that is step 1. in [your new doc in argocd example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/gitops/argocd/README.md#destroy):

> Disabling the `argocd_applications` configuration and running terraform apply again

The wording of this seems a little ambiguous to me. Don't you think that users would get the same effect by making the simpler change of changing `argocd_manage_add_ons` to `false`?

I was planning to just add an input variable to my root module for this boolean and have it default to true and have my destroy sequence set it to false using `terraform destroy -var='argocd_manage_add_ons=false' -target="module.eks_blueprints_kubernetes_addons"`.

If it's truly a requirement to leave `argocd_manage_add_ons = true` and set `argocd_applications = {}`, let me know.

**Comment by timblaktu** [comment]
There is a problem with the "Terraform" approach, that is step 1. in [your new doc in argocd example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/gitops/argocd/README.md#destroy):

> Disabling the argocd_applications configuration and running terraform apply again

which is that, if a subsequent `terraform destroy` step encounters some error, say, destroying `eks_blueprints`, and you retry the full destroy sequence including:

```
time terraform apply -var='cleanup_argocd_applications=true' -target="module.eks_blueprints_kubernetes_addons"
time terraform destroy -target="module.eks_blueprints_kubernetes_addons" 
time terraform destroy -target="module.eks_blueprints"
time terraform destroy
```

the targeted apply that is supposed to be _just cleaning up argocd applications_, ends up recreating a lot more infrastructure in the process, since it targets `eks_blueprints_kubernetes_addons` which depends on `eks_blueprints`.

I think I'll try the argoCD or kubectl approach instead. Seems like some of this detail belongs in the Guidance doc..

**Comment by Zvikan** [comment]
Hey @timblaktu , for the argocd example (as is, `main` branch [last commit](https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/65c99600a8c26476702e7e363fbb7b8d355b070d)) I can confirm that running target destroy (`-target="module.eks_blueprints_kubernetes_addons" `) to the k8s addons first makes the cleanup process smooth without any errors, I'm not even cleaning up argo applications before that.

My destroy workflow (in order) is:
```
terraform destroy -target="module.eks_blueprints_kubernetes_addons" -auto-approve
terraform destroy -auto-approve
```

**Comment by timblaktu** [comment]
@Zvikan what add-ons are you including in your test environment? Do they create external resources? This is key to this issue. Try managing Crossplane via argocd, with the crossplane aws provider specified. This will leak resources unless you gracefully delete the crossplane app first. I assume this fact is understood and accepted, thus the work done here to document it.

As for my comment about the targeted terraform apply approach not being robust, to repro that, just introduce an artificial error to occur in the later stage of your destruction sequence, e.g. a syntax error in some reference in eks_blueprints input variable. What happens is:

- argocd apps get deleted and crossplane leaks are "plugged"
- add-ons are destroyed successfully
- cluster and its supporting resources are partially destroyed.

On next destroy sequence, the targeted terraform apply approach in your new guidance doc ends up recreating the cluster (bc it's a dependency of the targeted resource, the addons). 

Aside from taking a lot of time, Depending on the error that happened in destroy, this can lead to complicated problems. So, what I'm suggesting is that the terraform approach be avoided or at least warned against in the docs bc the argocd cli or kubectl approaches are superior bc they are significantly faster and more robust.
