### ISSUE TITLE
Add support for configuration_values in native AWS addons configuration section

### ISSUE THREAD

**Issue by duclm2609** [aws-ia/terraform-aws-eks-blueprints#1304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
Terraform resource `aws_eks_addon` allows custom add-on configuration can be passed using `configuration_values` as a single JSON string while creating or updating the add-on. I want to be able to use this via, for example, section `amazon_eks_vpc_cni_config`. For now, to configure the addons, I have to use `local-exec` to run `kubectl` commands (by following the examples in this repository).

#### Describe the solution you would like
Add mapping for `configuration_values` value in each native AWS EKS addons modules.

#### Additional context

I can work on a pull request if this enhancement is accepted. Sorry for any typo as I'm not a native English speaker.
Thank you.

**Comment by lucaspouzac** [comment]
Example are updated with usage outside blueprint : https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1299

**Comment by Tommyf** [comment]
Yes, you can have these add-ons managed outside EKS Blueprints, but that had its own issues.

You can use `terraform-aws-modules/eks` to add the module (as per the new examples),but it will not create an IAM role for you. Instead, it will use the cluster default role, or you can create your own and pass that in.

While creating the IAM role using `terraform-aws-modules/iam` is not challenging in itself, it results in your IAM roles being defined in different, potentially inconsistent, ways.

It would be preferable to use the ELS Blueprints module to create these add-ons if you require an auto-generated IAM role. Unfortunately this is not possible if you want to also add `configuration_values` to the `aws_eks_addon` resource.

I agree that it would be ideal to add this mapping so that we can meet both of the above requirements easily.

**Comment by bryantbiggs** [comment]
closed in #1402
