### ISSUE TITLE
module irsa: allow input of additional assume role policy 

### ISSUE THREAD

**Issue by jz-xie** [aws-ia/terraform-aws-eks-blueprints#1470]
I was using irsa to create roles that need to be assumed by other IAM roles, for local testing purpose. But the irsa module does not allow additional assume role policy. Would be helpful to add a parameter called "irsa_iam_role_additional_policy", of type 'list(string)', to take additional trust policies.

I have tried to modify the assume role policy of an existing irsa role using Terraform but failed due to this open issue
https://github.com/hashicorp/terraform-provider-aws/issues/7922

**Comment by askulkarni2** [comment]
@jz-xie this seems like a custom use-case. Have you looked at constructing your own IRSA module through https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-group-with-assumable-roles-policy?

**Comment by bryantbiggs** [comment]
as @askulkarni2 mentioned, this is a unique/custom case and not something we recommend. IRSA roles for addons should be used only by those addons, otherwise users can gain access through the cluster through either https://github.com/aws-ia/terraform-aws-eks-blueprints-teams or other similar methods that are intended to facilitate user access

**Comment by jz-xie** [comment]
Thanks guys, I have solved my problem via a custom policy
