### ISSUE TITLE
Can't Rename Cluster / Run More than One EKS Blueprinter per Account with "karpenter" example.

### ISSUE THREAD

**Issue by DarwinJS** [aws-ia/terraform-aws-eks-blueprints#1548]
## Description
When I use variables.tf with defaults or with terraform.tfvars to make settings, the cluster_name variable is ignored and the cluster is called 'karpenter'

This also seems to effectively block more than one blueprint per account due to the global naming of some things with 'karpenter'.

Since I have not been able to get it to work, I don't know if all account level named items are even renamed by the action of renaming the cluster - so I'm hoping someone can confirm that.

If it is somehow working, it is not very easy to identify by the examples given. It would be nice to have the variables.tf / terraform.tfvars files full populated but also fully commented. This would make defaults evident, but also make configuration much simpler. This is a common approach in configuration files for various software - along with documenting comments.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version: 1.4.4

- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.62.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.19.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

variables.tf:

variable "cluster_name" {
  description = "EKS Cluster Name"
  type        = string
  default     = "cluster3"
}

terraform.auto.tfvars:
cluster_name = "cluster3"

With the above files in place, run the karpenter example as documented here: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/karpenter#deploy

## Expected behaviour

1. The EKS cluster should be named cluster3
2. All resources created by the IaC should be unique with 'cluster3' in their name somewhere.

## Actual behaviour

cluster_name placed in variables seem to be ignored. It seems cluster name might be hardcoded here: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/karpenter/main.tf#L65

But I also could not pass fargate_profiles, which is shown here: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/variables.tf#L355

I know the variable files are being used because when making syntax errors in them, it get's validation failures.

### Work Around
Direct editing main.tf does allow for an additional fargate_profiles item - but I have not tried renaming the cluster in main.tf yet.

**Comment by DarwinJS** [comment]
@bryantbiggs - I may be doing something wrong, but the merge does not appear to fix anything in this issue.

When I use the following in variables.tf  - the cluster name does not change and the fargate_profiles are not updated.

Can we please reopen this?

```
variable "cluster_name" {
  description = "EKS Cluster Name"
  type        = string
  default     = "runner"
}

variable "fargate_profiles" {
  description = "Fargate profile configuration"
  type        = string
  default     = <<EOT
{
    app_wildcard = {
        selectors = [
            { namespace = "gitlab-*" }
        ]
    }
    kube_system = {
        name = "kube-system"
        selectors = [
        { namespace = "kube-system" }
        ]
    }
    kube_system = {
        name = "kube-system"
        selectors = [
        { namespace = "kube-system" }
        ]
    }
}
EOT

}
```

**Comment by bryantbiggs** [comment]
it is resolved because we have resolved it in the new addons repository which is the direction we are working towards in v5. For now, we are not making any additional changes to the current project since we aim to resolve most of these issues with the v5 changes. You can see more details here https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1421

**Comment by DarwinJS** [comment]
@bryantbiggs - can you please point me to the issue that previously articulated the parameter ingestion problem that we know is solved in v5? Thanks!

**Comment by bryantbiggs** [comment]
Can you provide the reproduction code that demonstrates the issue you are encountering?

**Comment by DarwinJS** [comment]
@bryantbiggs - When I use the following variable specification in either the top level variables.tf or the /examples/karpenter level variables.tf, the values set in defaults appear to be completely ignored when executing terraform in /examples/karpenter. The cluster is named karpenter and the added fargate_profile is not created.

The fargate_profile IS created when I hack it directly into /examples/karpenter/main.tf.

This is for the soon to be published GitLab blog article: [Iteration 1 of GitLab EKS Fargate Runners in 1 Hour and Zero Lines of Code](https://content.gitlab.com/viewer/644121836130830cf93b0a6c)

```yaml
variable "cluster_name" {
  description = "EKS Cluster Name"
  type        = string
  default     = "runner"
}

variable "fargate_profiles" {
  description = "Fargate profile configuration"
  type        = string
  default     = <<EOT
{
    app_wildcard = {
        selectors = [
            { namespace = "gitlab-*" }
        ]
    }
    kube_system = {
        name = "kube-system"
        selectors = [
        { namespace = "kube-system" }
        ]
    }
    kube_system = {
        name = "kube-system"
        selectors = [
        { namespace = "kube-system" }
        ]
    }
}
EOT

}
```

**Comment by bryantbiggs** [comment]
ah ok now I see the issue. The provide patterns in EKS Blueprints are not intended to be consumed in place. Users can copy+paste the relevant bits into their repository, or simply refer to the patterns provided if they have their own custom Terraform implementation. 

To clarify:
1. Examples are not intended to be consumed in place - this is why we do not expose variables in examples because that would now define an interface and start to fall under semantic versioning, etc. Where variables are provided, it is because the example requires information from users in order to deploy (i.e. - API key, DNS hostname, etc.)
2. Modules are consumable and can be referenced through the usual module syntax. Theres are version controlled following semver and expose their interface through variables and outputs

**Comment by DarwinJS** [comment]
@bryantbiggs - so if I adapt the top level with the example files - then it should follow those two parameters?

**Comment by bryantbiggs** [comment]
Apologies but I am not quite following. What is the end goal that you are trying to achieve?

**Comment by DarwinJS** [comment]
To deploy a karpenter + fargate cluster that actually utilizes this parameter file rather than seeming to ignore the values.

```json
variable "cluster_name" {
  description = "EKS Cluster Name"
  type        = string
  default     = "runner"
}

variable "fargate_profiles" {
  description = "Fargate profile configuration"
  type        = string
  default     = <<EOT
{
    app_wildcard = {
        selectors = [
            { namespace = "gitlab-*" }
        ]
    }
    kube_system = {
        name = "kube-system"
        selectors = [
        { namespace = "kube-system" }
        ]
    }
    kube_system = {
        name = "kube-system"
        selectors = [
        { namespace = "kube-system" }
        ]
    }
}
EOT

}
```

**Comment by bryantbiggs** [comment]
ok, understood. And where is the rest of your configuration - the definition that you are passing these variables to?

**Comment by DarwinJS** [comment]
I was simply running the instructions in the readme.md of examples/karpenter in that folder - and running it there does work in every other regard - other than using the variables.

So as per our conversation on this thread, I am not understanding if all folders in examples are intended to be actually configured at the root of the entire project?

Maybe that what you meant by "The provide patterns in EKS Blueprints are not intended to be consumed in place." ?

**Comment by bryantbiggs** [comment]
The root of the project is a module - something that is intended to be consumed externally, which is why it exposes [variables](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/variables.tf) and [outputs](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/outputs.tf) (the inputs and outputs of its interface that can be consumed). 

Examples are not modules, and are not intended to be consumed externally - they are the implementation of module(s) and resource(s) composed to achieve an architectural outcome. Users can refer to these examples are replicate in their own projects and modify as they see fit.

This is why passing variables to the karpenter example has no effect, because [there aren't any variables exposed](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/karpenter/variables.tf). In addition, if it did support variables, you would not pass a variable definition as you have [shown above], but instead variable values through the various means that Terraform provides (a tfvars file, environment variables, CLI args, etc.)
