### ISSUE TITLE
Suggested Kubernetes Versions for EKS Blueprints

### ISSUE THREAD

**Issue by d-m** [aws-ia/terraform-aws-eks-blueprints#1555]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Are there suggested Kubernetes versions for each blueprint release? The default cluster variable shows [1.24](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/variables.tf#L57) but several of the modules have commits for supporting 1.25.

**Comment by bryantbiggs** [comment]
the suggestion is to use the latest version that you can to stay up to date - we don't necessarily need to align all examples to one specific version since they are just examples. When new EKS versions come out, we may need to tweak/update a few addon versions but otherwise things should just work as expected

**Comment by bryantbiggs** [comment]
closing with guidance provided above - please let us know if you have any additional questions, thank you!
