### ISSUE TITLE
Started getting this error subdir "modules/kubernetes-addons/helm-addon" not found

### ISSUE THREAD

**Issue by mk2134226** [aws-ia/terraform-aws-eks-blueprints#1630]
Everything was ok this morning but now started seeing this error

subdir "modules/kubernetes-addons/helm-addon" not found

**Comment by awarner-greshamtech** [comment]
Same. We pin the module version:
```
module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.27.0"
```

**Comment by vale21** [comment]
Same for us. 
We noticed that even if we pint a specific tag (v4.27.0) and sometimes it dowloads the correct version:

Downloading git::https://github.com/aws-ia/terraform-aws-eks-blueprints.git?ref=v4.27.0 for eks-cluster.eks_blueprints_kubernetes_addons...

there are a couple of internal modules that are downloading main:

Downloading git::https://github.com/aws-ia/terraform-aws-eks-blueprints.git for eks-cluster.eks_blueprints_kubernetes_addons.portworx.helm_addon...

Downloading git::https://github.com/aws-ia/terraform-aws-eks-blueprints.git for eks-cluster.eks_blueprints_kubernetes_addons.sysdig_agent.helm_addon...

**Comment by alexoughton** [comment]
I have found that this is due to calling external modules which do not pin to a specific release. For example:

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/80bd3b92e0f82f45a187805d6d847db320a01c31/modules/kubernetes-addons/main.tf#L391

which calls:

https://github.com/portworx/terraform-eksblueprints-portworx-addon/blob/bf6d1f68eee97052cac105563bebf19a5e6f4512/main.tf#L2

The problem is commit `19c7cfd` to `main` which removes the referenced directory in the external module. It appears that a coordination is required here to fix this in external modules which are called, and perhaps also publish another 4.x release to call those fixes.

**Comment by DanielCalvo** [comment]
Same here -- did an apply just fine this morning EU time and now its broken.

**Comment by yehoshoua** [comment]
Same here we use TAG 4.29

**Comment by yebolenko** [comment]
We have the same issue !!! Please fix. It also happens if we clone it locally (based on the tag).
If we use the local (cloned) repo, we still receive 
 Error: subdir "modules/kubernetes-addons/helm-addon" not found

**Comment by bryantbiggs** [comment]
we have temporarily re-added the two sub-modules that are un-pinned in the partner addons. Please let us know if this has temporarily resolved the issues 

In the meantime, we will work with the partner addons (those not defined here, just referenced here) to get their implementations updated/pinned

**Comment by alexoughton** [comment]
@bryantbiggs Yes, this appears to have resolved the issue, at least for me. Thanks for the quick action here.

**Comment by f-palma** [comment]
@bryantbiggs Yeah, it solved the issue. thanks!

**Comment by DanielCalvo** [comment]
Solved here as well -- thank you @bryantbiggs !

**Comment by bryantbiggs** [comment]
awesome - thank you all for confirming and apologies for the issues. It looks like we have a nasty little dynamic link that needs to be resolved

**Comment by bryantbiggs** [comment]
FYI - please update your EKS Blueprints module(s) to use the just released [v4.32.1](https://github.com/aws-ia/terraform-aws-eks-blueprints/releases/tag/v4.32.1)

We have PRs out to the partner's addons to ensure they pin the version of EKS Blueprints that they are referring to, but we have also created a static copy of their current addons and this is what is being referenced in v4.32.1 to eliminate this cyclical error. https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1634

(Read on if curious to understand what occurred today)

## What happened

Today we merged in a [large refactoring PR](https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1494) that removed all module definitions from the project as part of moving towards [v5 of EKS Blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1421). Normally this would have been a no-op for users since pinning module versions is always recommended - only those that were sourcing directly from the `main` branch, in theory, would have been affected - this is something that is outside of our control. However, due to the fact that:
1. In v4 the partner addon implementations were embedded into EKS Blueprints which means that on each Terraform initialization, Terraform reaches out to that modules definition to download its configurations
2. The partner module definitions utilize the EKS Blueprints v4 `helm-addon` sub-module. However, this sub-module was not pinned to a version and therefore referred EKS Blueprints `main` branch. 

In short, when the refactoring PR was merged, it removed the `helm-addon` sub-module from our `main` branch, which created the `subdir "modules/kubernetes-addons/helm-addon" not found` errors reported. The sub-modules were pointing at a moving target rather than a fixed point in time, and that moving target no longer had the `helm-addon` sub-module definition. This circular dependency is something that the team had identified awhile back and was one of the motivations for refactoring in v5 to externalize those utility/template modules (`helm-addon` and `irsa`) into a new, standalone module that lives on its own https://github.com/aws-ia/terraform-aws-eks-blueprints-addon. However, what we did not realize nor catch in any of the testing and validation - was the fact that partner addons pointing at `main` would break once that definition no longer exists on `main`. And for this, we apologize for the disruption caused today. 

## What steps are we taking to avoid this in the future

- First and foremost, we no longer allow modules embedded within modules without strict pinning. In addition, in v5, the modules have been refactor to remove 3rd party dependencies and offer better isolation from unintended changes outside of the module itself (flattened the hierarchy and reduced external dependencies outside of our control)
- We have temporarily re-added the sub-modules in question that were causing the issues reported when removed in #1632 
- We have opened PRs with the partner addons to apply a version pin to the `helm-addon` implementation
	- https://github.com/portworx/terraform-eksblueprints-portworx-addon/pull/15
	- https://github.com/tetratelabs/terraform-eksblueprints-tetrate-istio-addon/pull/13
	- https://github.com/sysdiglabs/terraform-eksblueprints-sysdig-addon/pull/49
- In addition, we have [copied the configurations from the partner addons into their respective local modules](https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1634). This is what removes the dynamic, cyclical link between EKS Blueprints -> the partner addon that contains the `helm-addon` module implementation -> EKS Blueprints `helm-module` definition.  This is a no-op change since the definitions are un-changed and changing module sources in Terraform do not create changes (i.e. - destroy and re-create). This is what is contained within the [v4.32.1](https://github.com/aws-ia/terraform-aws-eks-blueprints/releases/tag/v4.32.1) release 

With these changes in place, users are recommended to update to v4.32.1 to avoid any disruptions in the future when the `helm-addon` and `irsa` module definitions are re-removed from `main`. Please note - any version < 4.32.1 will be at risk of raising the errors reported in this issue when the `helm-addon` and `irsa` modules are re-removed from `main`. For example - version v4.12.0 is a static copy of configurations but it contains the 3rd party addons who's definitions are pointing back to EKS Blueprints `main` branch. 

If you have any questions or comments, please feel free to let us know here. Thank you and again, apologies for any disruptions from today's changes

**Comment by uje-m** [comment]
Hi @bryantbiggs 
I have pinned the module, but somehow after your merge.
I am experiencing the same error again.

subdir "modules/kubernetes-addons/helm-addon" not found

Do you know why it comes back?

**Comment by bryantbiggs** [comment]
are you using version 4.32.1?

**Comment by uje-m** [comment]
> 

Sorry, my mistake.
there's some project that still pinned to older version

**Comment by mambon2** [comment]
Upgrading to v4.32.1 seems to come with a weird quirk.  terraform plan always shows argocd_application["addons"] and argocd_application["workload"] have changed, even after apply.  Does anyone else run into this issue?

**Comment by abhijith-centrifuge** [comment]
github.com/aws-ia/terraform-aws-eks-blueprints//modules/irsa. 

I am looking for above module , code is breaking because of this . It was working fine before , is this moved to somewhere
