### ISSUE TITLE
Easy Q: How can I access older documentation on the Github Wiki?

### ISSUE THREAD

**Issue by jomakori** [aws-ia/terraform-aws-eks-blueprints#1762]
The [EKS blueprint wiki](https://aws-ia.github.io/terraform-aws-eks-blueprints/) has changed over time with the transition to v5. For those of us still running the legacy 4.x version of this template, how can we open their reference the older documentation for the sake of support/reference?

Thanks,

Joel

**Comment by bryantbiggs** [comment]
all of the history is still maintained within git and can be referenced by tags https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/v4.32.1

you can refer to both the source and the docs at that point in time - we are not rendering those prior versions on the GitHub pages because it was causing confusion and a lot of the prior doc links that were rendered pointed back at the repo which had since changed

**Comment by jomakori** [comment]
okay - no prob
Thanks Bryant!
