### ISSUE TITLE
[Bug]: the `kubernetes-dashboard` add-on does not install on EKS 1.22 due to the use of a deprecated API in the add-on ClusterRoleBinding manifest

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#463]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

b376059f695e33260dc4be7aedfdc5fe8d1d289d

### What is your environment, configuration and the example used?

```hcl
  enable_kubernetes_dashboard         = true
```

### What did you do and What did you see instead?

This manifest should take into account the EKS cluster version, so that it uses the correct API version.

At a minimum, it should be easy to override it.

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/kubernetes-dashboard/manifests/eks-admin-service-account.yaml#L1

**Comment by vara-bonthu** [comment]
@spkane Thanks for reporting the issue. We are yet to prove this module for EKS 1.22 with all the Add-ons. Few API versions have been removed in K8s 1.22 https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/. Some of these APIs now use `v1` instead of `v1beta1`.

We will apply a quick using cluster_version.

**Comment by spkane** [comment]
Exactly.

In this particular case, it appears to be the additional manifest that is added for the `ClusterRoleBinding` which is the problem, although there could be more issues in the helm release as well if it is significantly behind upstream.
