### ISSUE TITLE
[ADDON] KubeFlow Add-on support for EKS Blueprints

### ISSUE THREAD

**Issue by vara-bonthu** [aws-ia/terraform-aws-eks-blueprints#481]
#### Is your feature request related to a problem? Please describe

- This Add-on and example patterns helps customers who would like to use **KubeFlow on EKS** . This will extend the support for EKS Blueprints in Data Analytics and ML areas
-

**Comment by biljeff** [comment]
Standalone KFP would be an awesome add on. Should have the capability to create & use DynamoDB and S3 for pipeline config-map and caching.

**Comment by askulkarni2** [comment]
@biljeff this has been implemented [here](https://awslabs.github.io/kubeflow-manifests/docs/deployment/cognito-rds-s3/guide-terraform/). Please take a look when you get a chance. I will close this issue here as the kubeflow blueprints work is being tracked [here](https://github.com/awslabs/data-on-eks/issues/29).
