### ISSUE TITLE
[Bug]: terraform destroy fails when ingress via nginx is included

### ISSUE THREAD

**Issue by georgelza** [aws-ia/terraform-aws-eks-blueprints#524]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

1.21

### What is your environment, configuration and the example used?

Not sure how to replicate.
Noticed that when I have nginx configured for ingress, then a terraform destroy fails during destroy with various resources being locked, causing dependency destroy's to fail, (ie ALB, SG's, EIP's). Resulting to time lost due to manual deleting resources etc.

I can share my eks and nodegroups Tf files, to use to see if it can be reproduced.

G

### What did you do and What did you see instead?

-

### Additional Information

```shell
.
```

**Comment by Zvikan** [comment]
Thank you for reporting this @georgelza , can you please share the full example so we can try run and replicate the issue on our own account?

We need to carefully check what type of k8s resources are not being deleted properly, from my experience it usually starts with the namespace that stuck at "Terminating" state, usually that might lead into CRDs or other custom resources that are not being deleted properly by the helm addon/managed outside by webhook etc.
if it's a namespace hanging on terminating state type of issue I usually like to run: 
```
kubectl api-resources --verbs=list --namespaced -o name \\n  | xargs -n 1 kubectl get --show-kind --ignore-not-found -n <namespace>
```
This usually would show you what type of resources are left, manually you can work around this by removing the finalizers from the relevant resources that leads to this siutation.

**Comment by georgelza** [comment]
hmm, how can I attach a file, then i can zip my folder with the various Tf files execute as all part of the apply and destroy.

**Comment by georgelza** [comment]
Hi there...
The code is in a private git repo, so can't link, also as I offered to share the entire set of files thats executed via the terraform apply (it's 29 files) in the directory structure.

**Comment by Zvikan** [comment]
I see, in that case it's going to be more problematic to reproduce this issue if you can't share it.
Have you ran the command I shared [above](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/524#issuecomment-1122713052) and if you can please share the full error message and where it fails, we need more data in order to provide assistance with this.

Ideally we want to find the root cause of what's blocking your TF resources from being destroyed and dive deep to see if we can find a root cause and not just solving a symptoms in this case, as I mentioned above I've seen it happening with custom resources that are left behind and stopping namespaces that were created by TF from being destroyed properly.

**Comment by georgelza** [comment]
I created a new repo, copied the code into here.

https://github.com/georgelza/vpc_eks.git

This is my entire stack I create... which then fails a terraform destroy.

G

**Comment by Zvikan** [comment]
Hey @georgelza , 
I am able to reproduce the issue using your code:
```
module.eks_blueprints_kubernetes_addons.module.ingress_nginx[0].kubernetes_namespace_v1.this: Still destroying... [id=ingress-nginx, 4m50s elapsed]
╷
│ Warning: Version constraints inside provider configuration blocks are deprecated
│
│   on main.tf line 23, in provider "aws":
│   23:   version                  = ">= 3.72"
│
│ Terraform 0.13 and earlier allowed provider version constraints inside the provider configuration block, but that is now deprecated and will be removed in a future version of Terraform. To silence this
│ warning, move the provider version constraint into the required_providers block.
╵
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│
│   on .terraform/modules/eks_blueprints_kubernetes_addons.ondat/locals.tf line 2, in terraform:
│    2:   experiments = [module_variable_optional_attrs]
│
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
│
│ (and 70 more similar warnings elsewhere)
╵
╷
│ Error: context deadline exceeded
```


Can confirm the issue is namespace can't be deleted because its hanging on Terminating state:
```
➜  ~ kubectl get namespace
NAME              STATUS        AGE
default           Active        27m
ingress-nginx     Terminating   21m
kube-node-lease   Active        27m
kube-public       Active        27m
kube-system       Active        27m
```

I can see some pods are also stuck at terminating (nginx/cluster-autoscaler & ALB controller) , checking events I can see "node not ready" which lead me to check status of the nodes:
```
➜  ~ kubectl get nodes
NAME                                        STATUS     ROLES    AGE   VERSION
ip-10-7-24-229.us-west-2.compute.internal   NotReady   <none>   52m   v1.21.5-eks-9017834
ip-10-7-25-237.us-west-2.compute.internal   NotReady   <none>   52m   v1.21.5-eks-9017834
ip-10-7-26-58.us-west-2.compute.internal    NotReady   <none>   52m   v1.21.5-eks-9017834
ip-10-7-34-150.us-west-2.compute.internal   NotReady   <none>   52m   v1.21.5-eks-9017834
ip-10-7-34-254.us-west-2.compute.internal   NotReady   <none>   52m   v1.21.5-eks-9017834
ip-10-7-35-152.us-west-2.compute.internal   NotReady   <none>   52m   v1.21.5-eks-9017834
ip-10-7-35-94.us-west-2.compute.internal    NotReady   <none>   53m   v1.21.5-eks-9017834
ip-10-7-36-216.us-west-2.compute.internal   NotReady   <none>   52m   v1.21.5-eks-9017834
ip-10-7-36-55.us-west-2.compute.internal    NotReady   <none>   53m   v1.21.5-eks-9017834
```

As you can see the nodes are in status `NoReady` , which lead me to think that your project is probably running as one single TF apply/destroy, and you have multiple VPC resources (nat gateways, route tables etc.)  were destroyed before the addons were destroyed, which is not something you'd do (I hope :)).



Can you please confirm if you were running this with a single apply/destroy command? or did you use it by controlling the module(s) order using `-target` arg or any other way (e.g. implicit/explicit dependencies).

**Comment by georgelza** [comment]
Well glad we could reproduce it, always first challenge.
1. I run this as a single terraform apply ... Do my tests pack and then a single terraform destroy.
2. ok, so you were able to work around the problem by first destroying the add on's using the -target=<resource> and then the cluster similarly, which makes me think then doing a terraform destroy on the remaining will work?

**Comment by Zvikan** [comment]
@georgelza correct to your 2nd point, first you make sure to destroy addons only, then you can run destroy "all"

**Comment by georgelza** [comment]
... it's a fix... but the better fix would be for a single destroy to work...
i can make the add on's dependant on the EKS (think it is already) and then make the EKS dependant on ???
would this cause the destroy to correctly start with the add on's followed by the EKS and then transfers the rest of the stack ?

**Comment by armujahid** [comment]
I also faced same ` Error: context deadline exceeded` while destroying examples/karpenter cluster (after ensuring that no nodes are running created by Karpenter before running the `terraform Destroy`)  because node becomes unready first and therefore it's impossible to remove karpenter. It's stuck at terminating state. 

![image](https://user-images.githubusercontent.com/3725386/168428565-34e4bccf-9cd5-4dac-9053-706b290df0b0.png)

**Comment by Zvikan** [comment]
@georgelza , correct, you can add additional explicit dependencies via `depends_on`, as you have custom resources and modules used in your case, you can add it in areas where implicit dependencies doesn't get the job done.

Suggesting to also view [this thread](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/353#issuecomment-1121635755) for additional info.

@armujahid review your TF destroy logs, you may face same issue where VPC resources are deleted "too early", which leads to the same issue.

**Comment by Zvikan** [comment]
FYI - https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/580

**Comment by bryantbiggs** [comment]
Hi all - as @Zvikan stated, the current guidance is to do targeted destroys where addons are destroyed first. Unfortunately, Terraform does not know how to proceed to delete resources it does not have in its statefile (its control) which leads to these conflicts when resources created by addons via Kuberetes controllers are still present while Terraform is trying to tear down the infrastructure.

Please let us know if there are any other questions
