### ISSUE TITLE
[FEATURE] how can I use helm chart for aws-ebs-csi-driver

### ISSUE THREAD

**Issue by Hokwang** [aws-ia/terraform-aws-eks-blueprints#577]
Hi,

For now, I installed aws-ebs-csi-driver using helm chart.
Because I can set `storageClass` with it.

I think it is great benefit.

But blueprints' aws-ebs-csi-driver addon is not consider this way.

**Comment by bryantbiggs** [comment]
Hi @Hokwang - correct, the current implementation for the `aws-ebs-csi-driver` is through an EKS managed addon. We can look at providing an alternate route for deploying/managing through a Helm chart which will allow for custom configuration.

**Comment by Hokwang** [comment]
I think that all addons including vpc-cni will be removed. Because it is a prerequisite for installing other cni.
So if some addon has installing helm way, it is better to use.

**Comment by guilhermeblanco** [comment]
@Hokwang I too had the same issue.
I managed to preserve the EBS StorageClass by implementing a similar approach to the Helm chart in my own Terraform manifetss, like this:

```yaml
  # EBS CSI Driver
  enable_amazon_eks_aws_ebs_csi_driver = true
  amazon_eks_aws_ebs_csi_driver_config = {
    addon_name               = "aws-ebs-csi-driver"
    addon_version            = local.ebs_csi_driver_version
    resolve_conflicts        = "OVERWRITE"
    namespace                = "kube-system"
    additional_iam_policies  = []
    service_account_role_arn = ""
    tags                     = merge(var.tags, {
      Name = var.name
    })
  }

  # EFS CSI Driver
  enable_aws_efs_csi_driver      = true
  aws_efs_csi_driver_helm_config = {
    version    = "2.2.6"
    tags       = merge(var.tags, {
      Name = var.name
    })
  }
```

And later...

```hcl
resource "kubernetes_storage_class_v1" "ebs" {
  metadata {
    name = "ebs"
  }

  storage_provisioner    = "ebs.csi.aws.com"
  allow_volume_expansion = true
  reclaim_policy         = "Delete"
  volume_binding_mode    = "WaitForFirstConsumer"
  parameters             = {
    encrypted = true
    fsType    = "ext4"
    type      = "gp3"
  }
}
``` 

On first cluster I manually imported the storage class, then updated the Helm chart, then removed annotations, and many other steps in order to ensure the EBS StorageClass never got deleted. On subsequent clusters (I manage 5 big clusters), I just applied Terraform a few times sequentially and eventually everything worked out. In my case, as long as no auto scaling was happening during this transition, StorageClass was not used and everything worked like a charm.

PS: With EFS CSI Driver I did the same and it also worked well.

**Comment by Hokwang** [comment]
@guilhermeblanco Thanks for sharing your workaround. 🙌🏼
