### ISSUE TITLE
[QUESTION]  Error: error creating EKS Cluster (eks-cluster01): ResourceInUseException: Cluster already exists with name: eks-cluster01

### ISSUE THREAD

**Issue by kn0xyAU** [aws-ia/terraform-aws-eks-blueprints#636]
Hello EKS Community, 

I have been using EKS Blueprints 4.0.9 to deploy an EKS cluster, this deployed fine on the first run, but then I started to run into issues when trying to incrementally deploy changes to the cluster to modify it for our developers. I have come back from leave and tried to update Security groups and AWS-AUTH configmap to allow new users and roles access to the cluster. 

What causes this is when I added "cluster_additional_security_group_ids" then ran 'terraform plan then apply" I get this error message. I also added an additional ARN to the platform_teams block. 

After adding these changes to my main.tf and terraform apply (with a vars file) I get this issue:

Error: error creating EKS Cluster (eks-cluster01): ResourceInUseException: Cluster already exists with name: eks-cluster01
│ {
│   RespMetadata: {
│     StatusCode: 409,
│     RequestID: "e0a16273-addc-4bdb-96b0-d9e047d2272e"
│   },
│   ClusterName: "eks-cluster01",
│   Message_: "Cluster already exists with name: eks-cluster01"
│ }
│ 
│   with module.eks_blueprints.module.aws_eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks_blueprints.aws_eks/main.tf line 11, in resource "aws_eks_cluster" "this":
│   11: resource "aws_eks_cluster" "this" { 

---- part of my main.tf

module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.0.9"

  # EKS CLUSTER
  cluster_name              = var.cluster_name
  cluster_version           = "1.21"
  vpc_id                    = var.vpc_id
  private_subnet_ids        = var.private_subnets
  cluster_kms_key_arn       = "arn:aws:kms:xxxxxxxxx:xxxxxxxxx:key/xxxxxxxxxxxxxxxxx"
  iam_role_additional_policies = ["arn:aws:iam::xxxxxx:policy/kms-key-user-iam-policy"]
  cluster_additional_security_group_ids = ["${aws_security_group.ingress-eks-cluster01.id}"]

  platform_teams = {
    admin = {
      users = [
        data.aws_caller_identity.current.arn,
        "arn:aws:iam::xxxxxxxxxxxxx:role/aws-reserved/sso.amazonaws.com/xxxxxxxxxxx/AWSReservedSSO_xxxxxxxxxxxxxxxxxxx",
        "arn:aws:iam::xxxxxxxxxxxxxx:role/aws-reserved/sso.amazonaws.com/xxxxxxxxxxxxx/AWSReservedSSO_AWSAdministratorAccess_xxxxxxxxx"
        ]
    },
    clusteradminrole = {
      users = [
        "arn:aws:iam::xxxxxxxxxx:role/aws-reserved/sso.amazonaws.com/xxxxxxxxxxxAWSReservedSSO_xxxxxxxxxxxxxxxxx"
      ]
    }
  }
  map_users = [
----

I am still quite new to terraform so there could be something I have missed and apologies to the community if this is merely a lack of understanding my part. Any points would be awesome and thanks again for your time!

**Comment by bryantbiggs** [comment]
hi @kn0xyAU - certain changes will cause the cluster to be replaced since the API operations do not support in-place updates. Two that I know of off the top of my head are changing the cluster IAM role and the security group used by the cluster. Since you are making a change to the cluster security group, this is triggering the destroy/create cycle thats causing conflicts. If you are ok with the cluster being replaced, you could fully delete the cluster first with a `terraform destroy` and then re-provision with `terraform apply`, or you can change the name of the cluster in your Terraform code and simply `terraform apply`. 

I just want to be clear - this is a destructive operation and will destroy the cluster and all of its resources before provisioning new. please feel free to respond if you have any other questions, thanks!

**Comment by kn0xyAU** [comment]
Thank you very much for the response, noted and will keep an eye on things like this. I have changed my template to add those items and built a new cluster to ensure this doesn't trip me up again :) 

Thanks again!
