### ISSUE TITLE
[QUESTION] Why this module is not published in Terraform Registry?

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-eks-blueprints#775]
https://registry.terraform.io/browse/modules

**Comment by FernandoMiguel** [comment]
been asking myself the same question...
using pinned git releases is less practical than registry

**Comment by WesleyCharlesBlake** [comment]
https://registry.terraform.io/github/create

Repo maintainers just need to publish it here. I'd gladly do it if I got access @bryantbiggs

**Comment by askulkarni2** [comment]
Its a fair question and it is definitely something we had planned to do. I will bubble this up internally. Thanks!

**Comment by WesleyCharlesBlake** [comment]
Although one thing I did so we could manage this as a registry module, was  just fork the repo to my own org, and publish that. For those who are wanting this in a terraform registry, you could do that

**Comment by FernandoMiguel** [comment]
@askulkarni2 was there any progress on this topic?
is this something the team can include in a face to face discussion?

**Comment by JoGue1989** [comment]
It would be really nice because than you can also have things like version constraints on the module!

**Comment by gabe-villarreal** [comment]
Our company would like to use EKS Blueprints, as recommended by our AWS proservs, but we're unable to use it within our build environment due to it being nearly airgapped. We tried to use Artifactory to proxy it but Artifactory's Terraform proxying support is...limited (they can only proxy the main TF registry).

For now, we're having to do as others and clone this within our environment which isn't really sustainable.

**Comment by bryantbiggs** [comment]
please see https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1319

Any standalone modules will be migrated to their respective repositories and then published to the Terraform registry from there, similar to https://github.com/aws-ia/terraform-aws-eks-ack-addons
