### ISSUE TITLE
[Bug]: EKS Fully Private Cluster error authconfigmap

### ISSUE THREAD

**Issue by Ichigo974** [aws-ia/terraform-aws-eks-blueprints#824]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.6.1

### What is your environment, configuration and the example used?

![ekserror](https://user-images.githubusercontent.com/47851810/183078170-6dbbdd72-33b9-4d7e-90ed-00603fab8f84.PNG)

Hello,

I'm facing an issue when deploying eks fully private cluster.

module.eks_blueprints.module.aws_eks.aws_iam_openid_connect_provider.oidc_provider[0]: Creation complete after 1s [id=arn:aws:iam::589750301969:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/8EAF8E091161F4901C8FCC04E2B1A6E5]
╷
│ Error: Unauthorized
│ 
│   with module.eks_blueprints.kubernetes_config_map.aws_auth[0],
│   on ../../../aws-auth-configmap.tf line 1, in resource "kubernetes_config_map" "aws_auth":
│    1: resource "kubernetes_config_map" "aws_auth" {

Check the image pls 

Can you help me ?

Thx

### What did you do and What did you see instead?

search the module but i dont know what is missing

**Comment by henriquesantanati** [comment]
Hello @Ichigo974 , 

I just followed the [readme](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/fully-private-eks-cluster/README.md) file and I was able to run all commands without any issue.

Could you please elaborate more about what you are doing differently and also which is the step that is failing?

**Comment by Zvikan** [comment]
As @henriquesantanati  mentioned, since this example is using Cloud9, please make sure you followed the steps [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/fully-private-eks-cluster/README.md#provision-the-private-eks-cluster-using-the-eks-stack), especially step number 4:
```
Update IAM settings for your workspace to disable Cloud9 managing IAM credentials.

aws cloud9 update-environment  --environment-id $C9_PID --managed-credentials-action DISABLE
rm -vf ${HOME}/.aws/credentials
```

The cluster creation entity by default is considered "admin" of the cluster (not part of aws-auth), and it looks like the readiness script is working, so that tells me your c9 have access to the cluster, so I'm pretty sure when we run the aws_auth it's trying to using a different IAM entity, and you also shared that when running `update-kubeconfig` you are getting unauthorized.

You can confirm the above by checking:
1. Going to `CloudTrail` and check under event history the event `CreateCluster`, check the session username, it should be the c9 IAM role (I believe).
2. Then go to your c9 and run `aws sts get-caller-identity` , check that the same IAM role you saw in CloudTrail matching the output from the c9 AWS CLI command, if not, it means that you probably did not disable the managing IAM credentials (step 4 mentioned in the docs mentioned above).


Hope this helps!

**Comment by igorGevaerd** [comment]
I had this problem running the TF code from different accounts without configuring the VPC Peering. Make sure that it is not the case.

**Comment by rohancragg** [comment]
I'm having the same problem and I'm seeing the same username in CloudTrail event and in output from `get-caller-identity`.

I suspect I've not followed step 3. 

> 3. Create an IAM role for the Cloud9 workspace and attach the IAM role to your workspace. This IAM role should have enough permissions to provision an EKS cluster.

I don't understad how to do what's described in step 3, can anyone kindly clarify please?
