### ISSUE TITLE
[Bug] Add-on: aws-load-balancer deployed with ArgoCD, clusterName helm variable is missing

### ISSUE THREAD

**Issue by allamand** [aws-ia/terraform-aws-eks-blueprints#935]
## Description

When deploying aws-load-balancer-controller using ArgoCD it will fails to start with this error 👍 
```
execution error at (aws-load-balancer-controller/charts/aws-load-balancer-controller/templates/deployment.yaml:55:28): Chart cannot be installed without a valid clusterName! Use --debug flag to render out invalid YAML
```
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 1.4.2

- Terraform version: 1.1.9

- Provider version(s):

+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.29.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.8.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

## Reproduction Code [Required]

Deploy aws-load-balancer-controller with argocd
```
  argocd_manage_add_ons = true # Indicates that ArgoCD is responsible for managing/deploying Add-ons.
```

## Actual behaviour

The Helm is failing, but this seems normal as it is missing a required helm value:

https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/deployment.yaml#L61

This parameter is missing from the default helm values : https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/aws-load-balancer-controller/locals.tf#L41

But it is present if we deploy with terraform using the values.yaml https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/aws-load-balancer-controller/values.yaml#L1

**Comment by bryantbiggs** [comment]
Additional info - in general it looks like another case of Terraform based addon out of sync with GitOps based addon:
- [`serviceAccountName`](https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/chart/values.yaml#L39) should be [`serviceAccount.name`](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/aws-load-balancer-controller/locals.tf#L30)
- The default values provided via the [Terraform addon](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/aws-load-balancer-controller/values.yaml) allow for the AWS LBC to deploy correctly, but the [GItOps based addon](https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/chart/values.yaml#L37) does not since its missing required arguments (i.e. - cluster ID). These would presumably need to be passed across the "GitOps bridge"

**Comment by bryantbiggs** [comment]
closed in https://github.com/aws-samples/eks-blueprints-add-ons/pull/76
