### ISSUE TITLE
[Teams]Creating an application team for an existing namespace

### ISSUE THREAD

**Issue by sondrelg** [aws-ia/terraform-aws-eks-blueprints#975]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have an existing namespace that I would like to create an application team for. As far as I can tell there is no way to opt out of namespace creation for this module, but I also don't want to recreate the namespace. 

Do you know of any workarounds for this?

**Comment by Zvikan** [comment]
As of right now, the Teams module is not extended with features but we're definitely planning to re-work it to make it flexible for such needs. see https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/842 for more info.
If you have any other design requests to us around the teams module, feel free to throw that in the issue I linked.

The only workaround I see right now is to fork the code and modify it to use existing namespace if provided instead of creating one.

**Comment by bryantbiggs** [comment]
referenced in #942, closing to consolidate

**Comment by sondrelg** [comment]
Did you link the wrong issue @bryantbiggs - not sure I understand how this is related to #942

**Comment by bryantbiggs** [comment]
Whoops - close but off by one (*100) 😅 - see #842

**Comment by sondrelg** [comment]
Awesome, thanks!
